# coding: utf-8
try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from cloudtower.configuration import Configuration


class BackupPlanExecutionOrderByInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DELETABLE_FLAG_MARKED_ASC = "deletable_flag_marked_ASC"
    DELETABLE_FLAG_MARKED_DESC = "deletable_flag_marked_DESC"
    DURATION_ASC = "duration_ASC"
    DURATION_DESC = "duration_DESC"
    ENTITYASYNCSTATUS_ASC = "entityAsyncStatus_ASC"
    ENTITYASYNCSTATUS_DESC = "entityAsyncStatus_DESC"
    EXECUTED_AT_ASC = "executed_at_ASC"
    EXECUTED_AT_DESC = "executed_at_DESC"
    ID_ASC = "id_ASC"
    ID_DESC = "id_DESC"
    LOCAL_CREATED_AT_ASC = "local_created_at_ASC"
    LOCAL_CREATED_AT_DESC = "local_created_at_DESC"
    LOCAL_ID_ASC = "local_id_ASC"
    LOCAL_ID_DESC = "local_id_DESC"
    METHOD_ASC = "method_ASC"
    METHOD_DESC = "method_DESC"
    STATE_ASC = "state_ASC"
    STATE_DESC = "state_DESC"
    STATUS_ASC = "status_ASC"
    STATUS_DESC = "status_DESC"
    SUCCESS_JOB_COUNT_ASC = "success_job_count_ASC"
    SUCCESS_JOB_COUNT_DESC = "success_job_count_DESC"
    TOTAL_JOB_COUNT_ASC = "total_job_count_ASC"
    TOTAL_JOB_COUNT_DESC = "total_job_count_DESC"
    TYPE_ASC = "type_ASC"
    TYPE_DESC = "type_DESC"

    allowable_values = [DELETABLE_FLAG_MARKED_ASC, DELETABLE_FLAG_MARKED_DESC, DURATION_ASC, DURATION_DESC, ENTITYASYNCSTATUS_ASC, ENTITYASYNCSTATUS_DESC, EXECUTED_AT_ASC, EXECUTED_AT_DESC, ID_ASC, ID_DESC, LOCAL_CREATED_AT_ASC, LOCAL_CREATED_AT_DESC, LOCAL_ID_ASC, LOCAL_ID_DESC, METHOD_ASC, METHOD_DESC, STATE_ASC, STATE_DESC, STATUS_ASC, STATUS_DESC, SUCCESS_JOB_COUNT_ASC, SUCCESS_JOB_COUNT_DESC, TOTAL_JOB_COUNT_ASC, TOTAL_JOB_COUNT_DESC, TYPE_ASC, TYPE_DESC]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self, **kwargs):  # noqa: E501
        """BackupPlanExecutionOrderByInput - a model defined in OpenAPI"""  # noqa: E501
        self.local_vars_configuration = kwargs.get("local_vars_configuration", Configuration.get_default_copy())
        self.discriminator = None

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackupPlanExecutionOrderByInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BackupPlanExecutionOrderByInput):
            return True

        return self.to_dict() != other.to_dict()
