# coding: utf-8
try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from cloudtower.configuration import Configuration


class ClusterRecycleBinCreationParamsData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'retain': 'int',
        'enabled': 'bool'
    }

    attribute_map = {
        'retain': 'retain',
        'enabled': 'enabled'
    }

    def __init__(self, **kwargs):  # noqa: E501
        """ClusterRecycleBinCreationParamsData - a model defined in OpenAPI"""  # noqa: E501
        self.local_vars_configuration = kwargs.get("local_vars_configuration", Configuration.get_default_copy())

        self._retain = None
        self._enabled = None
        self.discriminator = None

        if "retain" in kwargs:
            self.retain = kwargs["retain"]
        if "enabled" in kwargs:
            self.enabled = kwargs["enabled"]

    @property
    def retain(self):
        """Gets the retain of this ClusterRecycleBinCreationParamsData.  # noqa: E501


        :return: The retain of this ClusterRecycleBinCreationParamsData.  # noqa: E501
        :rtype: int
        """
        return self._retain

    @retain.setter
    def retain(self, retain):
        """Sets the retain of this ClusterRecycleBinCreationParamsData.


        :param retain: The retain of this ClusterRecycleBinCreationParamsData.  # noqa: E501
        :type retain: int
        """
        if self.local_vars_configuration.client_side_validation and retain is None:  # noqa: E501
            raise ValueError("Invalid value for `retain`, must not be `None`")  # noqa: E501

        self._retain = retain

    @property
    def enabled(self):
        """Gets the enabled of this ClusterRecycleBinCreationParamsData.  # noqa: E501


        :return: The enabled of this ClusterRecycleBinCreationParamsData.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ClusterRecycleBinCreationParamsData.


        :param enabled: The enabled of this ClusterRecycleBinCreationParamsData.  # noqa: E501
        :type enabled: bool
        """
        if self.local_vars_configuration.client_side_validation and enabled is None:  # noqa: E501
            raise ValueError("Invalid value for `enabled`, must not be `None`")  # noqa: E501

        self._enabled = enabled

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterRecycleBinCreationParamsData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ClusterRecycleBinCreationParamsData):
            return True

        return self.to_dict() != other.to_dict()
