# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.nested_everoute_cluster_controller_status import NestedEverouteClusterControllerStatus  # noqa: E501
from cloudtower.rest import ApiException

class TestNestedEverouteClusterControllerStatus(unittest.TestCase):
    """NestedEverouteClusterControllerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NestedEverouteClusterControllerStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.nested_everoute_cluster_controller_status.NestedEverouteClusterControllerStatus()  # noqa: E501
        if include_optional :
            return NestedEverouteClusterControllerStatus(
                current_number = 56, 
                expect_number = 56, 
                instances = [
                    cloudtower.models.nested_everoute_controller_status.NestedEverouteControllerStatus(
                        ip_addr = '', 
                        is_health = True, 
                        message = '', 
                        metrics = null, 
                        phase = null, 
                        reason = '', 
                        vm = null, 
                        vm_id = '', )
                    ], 
                number_health = 56
            )
        else :
            return NestedEverouteClusterControllerStatus(
                current_number = 56,
                expect_number = 56,
                number_health = 56,
        )

    def testNestedEverouteClusterControllerStatus(self):
        """Test NestedEverouteClusterControllerStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
