# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.nvmf_subsystem_creation_params_all_of import NvmfSubsystemCreationParamsAllOf  # noqa: E501
from cloudtower.rest import ApiException

class TestNvmfSubsystemCreationParamsAllOf(unittest.TestCase):
    """NvmfSubsystemCreationParamsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NvmfSubsystemCreationParamsAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.nvmf_subsystem_creation_params_all_of.NvmfSubsystemCreationParamsAllOf()  # noqa: E501
        if include_optional :
            return NvmfSubsystemCreationParamsAllOf(
                replica_num = 56, 
                thin_provision = True, 
                stripe_size = 56, 
                stripe_num = 56, 
                policy = 'BALANCE', 
                cluster_id = '', 
                name = ''
            )
        else :
            return NvmfSubsystemCreationParamsAllOf(
                replica_num = 56,
                thin_provision = True,
                stripe_size = 56,
                stripe_num = 56,
                policy = 'BALANCE',
                cluster_id = '',
                name = '',
        )

    def testNvmfSubsystemCreationParamsAllOf(self):
        """Test NvmfSubsystemCreationParamsAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
