# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.with_task_snmp_trap_receiver import WithTaskSnmpTrapReceiver  # noqa: E501
from cloudtower.rest import ApiException

class TestWithTaskSnmpTrapReceiver(unittest.TestCase):
    """WithTaskSnmpTrapReceiver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WithTaskSnmpTrapReceiver
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.with_task_snmp_trap_receiver.WithTaskSnmpTrapReceiver()  # noqa: E501
        if include_optional :
            return WithTaskSnmpTrapReceiver(
                task_id = '', 
                data = cloudtower.models.snmp_trap_receiver.SnmpTrapReceiver(
                    auth_pass_phrase = '', 
                    auth_protocol = null, 
                    cluster = cloudtower.models.nested_cluster.NestedCluster(
                        id = '', 
                        name = '', ), 
                    community = '', 
                    disabled = True, 
                    engine_id = '', 
                    entity_async_status = null, 
                    host = '', 
                    id = '', 
                    inform = True, 
                    language_code = 'EN_US', 
                    local_id = '', 
                    name = '', 
                    port = 56, 
                    privacy_pass_phrase = '', 
                    privacy_protocol = null, 
                    protocol = 'TCP', 
                    username = '', 
                    version = 'V2C', )
            )
        else :
            return WithTaskSnmpTrapReceiver(
                data = cloudtower.models.snmp_trap_receiver.SnmpTrapReceiver(
                    auth_pass_phrase = '', 
                    auth_protocol = null, 
                    cluster = cloudtower.models.nested_cluster.NestedCluster(
                        id = '', 
                        name = '', ), 
                    community = '', 
                    disabled = True, 
                    engine_id = '', 
                    entity_async_status = null, 
                    host = '', 
                    id = '', 
                    inform = True, 
                    language_code = 'EN_US', 
                    local_id = '', 
                    name = '', 
                    port = 56, 
                    privacy_pass_phrase = '', 
                    privacy_protocol = null, 
                    protocol = 'TCP', 
                    username = '', 
                    version = 'V2C', ),
        )

    def testWithTaskSnmpTrapReceiver(self):
        """Test WithTaskSnmpTrapReceiver"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
