# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.vm_firmware import VmFirmware  # noqa: E501
from cloudtower.rest import ApiException

class TestVmFirmware(unittest.TestCase):
    """VmFirmware unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VmFirmware
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.vm_firmware.VmFirmware()  # noqa: E501
        if include_optional :
            return VmFirmware(
            )
        else :
            return VmFirmware(
        )

    def testVmFirmware(self):
        """Test VmFirmware"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
