# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.vm_update_nic_advance_info_params_data import VmUpdateNicAdvanceInfoParamsData  # noqa: E501
from cloudtower.rest import ApiException

class TestVmUpdateNicAdvanceInfoParamsData(unittest.TestCase):
    """VmUpdateNicAdvanceInfoParamsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VmUpdateNicAdvanceInfoParamsData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.vm_update_nic_advance_info_params_data.VmUpdateNicAdvanceInfoParamsData()  # noqa: E501
        if include_optional :
            return VmUpdateNicAdvanceInfoParamsData(
                mirror = True, 
                enabled = True, 
                mac_address = '', 
                nic_id = '', 
                connect_vlan_id = ''
            )
        else :
            return VmUpdateNicAdvanceInfoParamsData(
        )

    def testVmUpdateNicAdvanceInfoParamsData(self):
        """Test VmUpdateNicAdvanceInfoParamsData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
