# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.with_task_batch_hosts import WithTaskBatchHosts  # noqa: E501
from cloudtower.rest import ApiException

class TestWithTaskBatchHosts(unittest.TestCase):
    """WithTaskBatchHosts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WithTaskBatchHosts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.with_task_batch_hosts.WithTaskBatchHosts()  # noqa: E501
        if include_optional :
            return WithTaskBatchHosts(
                task_id = '', 
                data = cloudtower.models.batch_hosts.BatchHosts(
                    task = cloudtower.models.nested_task.NestedTask(
                        args = cloudtower.models.args.args(), 
                        description = '', 
                        id = '', 
                        internal = True, 
                        local_created_at = '', 
                        progress = 1.337, 
                        snapshot = '', 
                        status = 'EXECUTING', 
                        steps = [
                            cloudtower.models.nested_step.NestedStep(
                                current = 1.337, 
                                finished = True, 
                                key = '', 
                                per_second = 1.337, 
                                total = 1.337, 
                                unit = null, )
                            ], ), )
            )
        else :
            return WithTaskBatchHosts(
                data = cloudtower.models.batch_hosts.BatchHosts(
                    task = cloudtower.models.nested_task.NestedTask(
                        args = cloudtower.models.args.args(), 
                        description = '', 
                        id = '', 
                        internal = True, 
                        local_created_at = '', 
                        progress = 1.337, 
                        snapshot = '', 
                        status = 'EXECUTING', 
                        steps = [
                            cloudtower.models.nested_step.NestedStep(
                                current = 1.337, 
                                finished = True, 
                                key = '', 
                                per_second = 1.337, 
                                total = 1.337, 
                                unit = null, )
                            ], ), ),
        )

    def testWithTaskBatchHosts(self):
        """Test WithTaskBatchHosts"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
