# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudtower
from cloudtower.models.with_task_vm_snapshot import WithTaskVmSnapshot  # noqa: E501
from cloudtower.rest import ApiException

class TestWithTaskVmSnapshot(unittest.TestCase):
    """WithTaskVmSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WithTaskVmSnapshot
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudtower.models.with_task_vm_snapshot.WithTaskVmSnapshot()  # noqa: E501
        if include_optional :
            return WithTaskVmSnapshot(
                task_id = '', 
                data = cloudtower.models.vm_snapshot.VmSnapshot(
                    clock_offset = 'LOCALTIME', 
                    cluster = cloudtower.models.nested_cluster.NestedCluster(
                        id = '', 
                        name = '', ), 
                    consistent_type = 'CRASH_CONSISTENT', 
                    cpu = cloudtower.models.nested_cpu.NestedCpu(
                        cores = 56, 
                        sockets = 56, ), 
                    cpu_model = '', 
                    description = '', 
                    entity_async_status = null, 
                    firmware = 'BIOS', 
                    ha = True, 
                    id = '', 
                    io_policy = null, 
                    labels = [
                        cloudtower.models.nested_label.NestedLabel(
                            id = '', )
                        ], 
                    local_created_at = '', 
                    local_id = '', 
                    max_bandwidth = 56, 
                    max_bandwidth_policy = null, 
                    max_iops = 56, 
                    max_iops_policy = null, 
                    memory = 56, 
                    name = '', 
                    size = 56, 
                    snapshot_group = null, 
                    vcpu = 56, 
                    vm = null, 
                    vm_disks = [
                        cloudtower.models.nested_frozen_disks.NestedFrozenDisks(
                            boot = 56, 
                            bus = 'IDE', 
                            disabled = True, 
                            disk_name = '', 
                            elf_image_local_id = '', 
                            image_name = '', 
                            index = 56, 
                            key = 56, 
                            max_bandwidth = 56, 
                            max_bandwidth_policy = null, 
                            max_iops = 56, 
                            max_iops_policy = null, 
                            path = '', 
                            size = 56, 
                            snapshot_local_id = '', 
                            storage_policy_uuid = '', 
                            svt_image_local_id = '', 
                            type = 'CD_ROM', 
                            vm_volume_local_id = '', 
                            vm_volume_snapshot_uuid = '', 
                            vm_volume_template_uuid = '', )
                        ], 
                    vm_nics = [
                        cloudtower.models.nested_frozen_nic.NestedFrozenNic(
                            enabled = True, 
                            gateway = '', 
                            index = 56, 
                            ip_address = '', 
                            mac_address = '', 
                            mirror = True, 
                            model = null, 
                            subnet_mask = '', 
                            vlan = cloudtower.models.nested_frozen_vlan.NestedFrozenVlan(
                                name = '', 
                                vds_ovs = '', 
                                vlan_id = 56, 
                                vlan_local_id = '', ), )
                        ], 
                    win_opt = True, )
            )
        else :
            return WithTaskVmSnapshot(
                data = cloudtower.models.vm_snapshot.VmSnapshot(
                    clock_offset = 'LOCALTIME', 
                    cluster = cloudtower.models.nested_cluster.NestedCluster(
                        id = '', 
                        name = '', ), 
                    consistent_type = 'CRASH_CONSISTENT', 
                    cpu = cloudtower.models.nested_cpu.NestedCpu(
                        cores = 56, 
                        sockets = 56, ), 
                    cpu_model = '', 
                    description = '', 
                    entity_async_status = null, 
                    firmware = 'BIOS', 
                    ha = True, 
                    id = '', 
                    io_policy = null, 
                    labels = [
                        cloudtower.models.nested_label.NestedLabel(
                            id = '', )
                        ], 
                    local_created_at = '', 
                    local_id = '', 
                    max_bandwidth = 56, 
                    max_bandwidth_policy = null, 
                    max_iops = 56, 
                    max_iops_policy = null, 
                    memory = 56, 
                    name = '', 
                    size = 56, 
                    snapshot_group = null, 
                    vcpu = 56, 
                    vm = null, 
                    vm_disks = [
                        cloudtower.models.nested_frozen_disks.NestedFrozenDisks(
                            boot = 56, 
                            bus = 'IDE', 
                            disabled = True, 
                            disk_name = '', 
                            elf_image_local_id = '', 
                            image_name = '', 
                            index = 56, 
                            key = 56, 
                            max_bandwidth = 56, 
                            max_bandwidth_policy = null, 
                            max_iops = 56, 
                            max_iops_policy = null, 
                            path = '', 
                            size = 56, 
                            snapshot_local_id = '', 
                            storage_policy_uuid = '', 
                            svt_image_local_id = '', 
                            type = 'CD_ROM', 
                            vm_volume_local_id = '', 
                            vm_volume_snapshot_uuid = '', 
                            vm_volume_template_uuid = '', )
                        ], 
                    vm_nics = [
                        cloudtower.models.nested_frozen_nic.NestedFrozenNic(
                            enabled = True, 
                            gateway = '', 
                            index = 56, 
                            ip_address = '', 
                            mac_address = '', 
                            mirror = True, 
                            model = null, 
                            subnet_mask = '', 
                            vlan = cloudtower.models.nested_frozen_vlan.NestedFrozenVlan(
                                name = '', 
                                vds_ovs = '', 
                                vlan_id = 56, 
                                vlan_local_id = '', ), )
                        ], 
                    win_opt = True, ),
        )

    def testWithTaskVmSnapshot(self):
        """Test WithTaskVmSnapshot"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
