# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cloudtower
from cloudtower.api.svt_image_api import SvtImageApi  # noqa: E501
from cloudtower.rest import ApiException


class TestSvtImageApi(unittest.TestCase):
    """SvtImageApi unit test stubs"""

    def setUp(self):
        self.api = cloudtower.api.svt_image_api.SvtImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_svt_images(self):
        """Test case for get_svt_images

        """
        pass

    def test_get_svt_images_connection(self):
        """Test case for get_svt_images_connection

        """
        pass

    def test_upload_svt_image(self):
        """Test case for upload_svt_image

        """
        pass


if __name__ == '__main__':
    unittest.main()
