# coding: utf-8

"""
    CloudTower APIs

    cloudtower operation API and SDK  # noqa: E501

    The version of the OpenAPI document: 1.9.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from cloudtower_python_sdk.configuration import Configuration


class NvmfSubsystemCreationParams(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'replica_num': 'int',
        'thin_provision': 'bool',
        'stripe_size': 'float',
        'stripe_num': 'int',
        'policy': 'NvmfSubsystemPolicyType',
        'cluster_id': 'str',
        'name': 'str',
        'bps_wr_max_length': 'float',
        'bps_wr_max': 'float',
        'bps_rd_max_length': 'float',
        'bps_rd_max': 'float',
        'bps_max_length': 'float',
        'bps_max': 'float',
        'iops_wr_max_length': 'float',
        'iops_wr_max': 'float',
        'iops_rd_max_length': 'float',
        'iops_rd_max': 'float',
        'iops_max_length': 'float',
        'iops_max': 'float',
        'bps_wr': 'float',
        'bps_rd': 'float',
        'bps': 'float',
        'iops_wr': 'float',
        'iops_rd': 'float',
        'iops': 'float',
        'description': 'str',
        'nqn_whitelist': 'str',
        'ip_whitelist': 'str'
    }

    attribute_map = {
        'replica_num': 'replica_num',
        'thin_provision': 'thin_provision',
        'stripe_size': 'stripe_size',
        'stripe_num': 'stripe_num',
        'policy': 'policy',
        'cluster_id': 'cluster_id',
        'name': 'name',
        'bps_wr_max_length': 'bps_wr_max_length',
        'bps_wr_max': 'bps_wr_max',
        'bps_rd_max_length': 'bps_rd_max_length',
        'bps_rd_max': 'bps_rd_max',
        'bps_max_length': 'bps_max_length',
        'bps_max': 'bps_max',
        'iops_wr_max_length': 'iops_wr_max_length',
        'iops_wr_max': 'iops_wr_max',
        'iops_rd_max_length': 'iops_rd_max_length',
        'iops_rd_max': 'iops_rd_max',
        'iops_max_length': 'iops_max_length',
        'iops_max': 'iops_max',
        'bps_wr': 'bps_wr',
        'bps_rd': 'bps_rd',
        'bps': 'bps',
        'iops_wr': 'iops_wr',
        'iops_rd': 'iops_rd',
        'iops': 'iops',
        'description': 'description',
        'nqn_whitelist': 'nqn_whitelist',
        'ip_whitelist': 'ip_whitelist'
    }

    def __init__(self, replica_num=None, thin_provision=None, stripe_size=None, stripe_num=None, policy=None, cluster_id=None, name=None, bps_wr_max_length=None, bps_wr_max=None, bps_rd_max_length=None, bps_rd_max=None, bps_max_length=None, bps_max=None, iops_wr_max_length=None, iops_wr_max=None, iops_rd_max_length=None, iops_rd_max=None, iops_max_length=None, iops_max=None, bps_wr=None, bps_rd=None, bps=None, iops_wr=None, iops_rd=None, iops=None, description=None, nqn_whitelist=None, ip_whitelist=None, local_vars_configuration=None):  # noqa: E501
        """NvmfSubsystemCreationParams - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._replica_num = None
        self._thin_provision = None
        self._stripe_size = None
        self._stripe_num = None
        self._policy = None
        self._cluster_id = None
        self._name = None
        self._bps_wr_max_length = None
        self._bps_wr_max = None
        self._bps_rd_max_length = None
        self._bps_rd_max = None
        self._bps_max_length = None
        self._bps_max = None
        self._iops_wr_max_length = None
        self._iops_wr_max = None
        self._iops_rd_max_length = None
        self._iops_rd_max = None
        self._iops_max_length = None
        self._iops_max = None
        self._bps_wr = None
        self._bps_rd = None
        self._bps = None
        self._iops_wr = None
        self._iops_rd = None
        self._iops = None
        self._description = None
        self._nqn_whitelist = None
        self._ip_whitelist = None
        self.discriminator = None

        self.replica_num = replica_num
        self.thin_provision = thin_provision
        self.stripe_size = stripe_size
        self.stripe_num = stripe_num
        self.policy = policy
        self.cluster_id = cluster_id
        self.name = name
        if bps_wr_max_length is not None:
            self.bps_wr_max_length = bps_wr_max_length
        if bps_wr_max is not None:
            self.bps_wr_max = bps_wr_max
        if bps_rd_max_length is not None:
            self.bps_rd_max_length = bps_rd_max_length
        if bps_rd_max is not None:
            self.bps_rd_max = bps_rd_max
        if bps_max_length is not None:
            self.bps_max_length = bps_max_length
        if bps_max is not None:
            self.bps_max = bps_max
        if iops_wr_max_length is not None:
            self.iops_wr_max_length = iops_wr_max_length
        if iops_wr_max is not None:
            self.iops_wr_max = iops_wr_max
        if iops_rd_max_length is not None:
            self.iops_rd_max_length = iops_rd_max_length
        if iops_rd_max is not None:
            self.iops_rd_max = iops_rd_max
        if iops_max_length is not None:
            self.iops_max_length = iops_max_length
        if iops_max is not None:
            self.iops_max = iops_max
        if bps_wr is not None:
            self.bps_wr = bps_wr
        if bps_rd is not None:
            self.bps_rd = bps_rd
        if bps is not None:
            self.bps = bps
        if iops_wr is not None:
            self.iops_wr = iops_wr
        if iops_rd is not None:
            self.iops_rd = iops_rd
        if iops is not None:
            self.iops = iops
        if description is not None:
            self.description = description
        if nqn_whitelist is not None:
            self.nqn_whitelist = nqn_whitelist
        if ip_whitelist is not None:
            self.ip_whitelist = ip_whitelist

    @property
    def replica_num(self):
        """Gets the replica_num of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The replica_num of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: int
        """
        return self._replica_num

    @replica_num.setter
    def replica_num(self, replica_num):
        """Sets the replica_num of this NvmfSubsystemCreationParams.


        :param replica_num: The replica_num of this NvmfSubsystemCreationParams.  # noqa: E501
        :type replica_num: int
        """
        if self.local_vars_configuration.client_side_validation and replica_num is None:  # noqa: E501
            raise ValueError("Invalid value for `replica_num`, must not be `None`")  # noqa: E501

        self._replica_num = replica_num

    @property
    def thin_provision(self):
        """Gets the thin_provision of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The thin_provision of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: bool
        """
        return self._thin_provision

    @thin_provision.setter
    def thin_provision(self, thin_provision):
        """Sets the thin_provision of this NvmfSubsystemCreationParams.


        :param thin_provision: The thin_provision of this NvmfSubsystemCreationParams.  # noqa: E501
        :type thin_provision: bool
        """
        if self.local_vars_configuration.client_side_validation and thin_provision is None:  # noqa: E501
            raise ValueError("Invalid value for `thin_provision`, must not be `None`")  # noqa: E501

        self._thin_provision = thin_provision

    @property
    def stripe_size(self):
        """Gets the stripe_size of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The stripe_size of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._stripe_size

    @stripe_size.setter
    def stripe_size(self, stripe_size):
        """Sets the stripe_size of this NvmfSubsystemCreationParams.


        :param stripe_size: The stripe_size of this NvmfSubsystemCreationParams.  # noqa: E501
        :type stripe_size: float
        """
        if self.local_vars_configuration.client_side_validation and stripe_size is None:  # noqa: E501
            raise ValueError("Invalid value for `stripe_size`, must not be `None`")  # noqa: E501

        self._stripe_size = stripe_size

    @property
    def stripe_num(self):
        """Gets the stripe_num of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The stripe_num of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: int
        """
        return self._stripe_num

    @stripe_num.setter
    def stripe_num(self, stripe_num):
        """Sets the stripe_num of this NvmfSubsystemCreationParams.


        :param stripe_num: The stripe_num of this NvmfSubsystemCreationParams.  # noqa: E501
        :type stripe_num: int
        """
        if self.local_vars_configuration.client_side_validation and stripe_num is None:  # noqa: E501
            raise ValueError("Invalid value for `stripe_num`, must not be `None`")  # noqa: E501

        self._stripe_num = stripe_num

    @property
    def policy(self):
        """Gets the policy of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The policy of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: NvmfSubsystemPolicyType
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this NvmfSubsystemCreationParams.


        :param policy: The policy of this NvmfSubsystemCreationParams.  # noqa: E501
        :type policy: NvmfSubsystemPolicyType
        """
        if self.local_vars_configuration.client_side_validation and policy is None:  # noqa: E501
            raise ValueError("Invalid value for `policy`, must not be `None`")  # noqa: E501

        self._policy = policy

    @property
    def cluster_id(self):
        """Gets the cluster_id of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The cluster_id of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this NvmfSubsystemCreationParams.


        :param cluster_id: The cluster_id of this NvmfSubsystemCreationParams.  # noqa: E501
        :type cluster_id: str
        """
        if self.local_vars_configuration.client_side_validation and cluster_id is None:  # noqa: E501
            raise ValueError("Invalid value for `cluster_id`, must not be `None`")  # noqa: E501

        self._cluster_id = cluster_id

    @property
    def name(self):
        """Gets the name of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The name of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NvmfSubsystemCreationParams.


        :param name: The name of this NvmfSubsystemCreationParams.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def bps_wr_max_length(self):
        """Gets the bps_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_wr_max_length

    @bps_wr_max_length.setter
    def bps_wr_max_length(self, bps_wr_max_length):
        """Sets the bps_wr_max_length of this NvmfSubsystemCreationParams.


        :param bps_wr_max_length: The bps_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_wr_max_length: float
        """

        self._bps_wr_max_length = bps_wr_max_length

    @property
    def bps_wr_max(self):
        """Gets the bps_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_wr_max

    @bps_wr_max.setter
    def bps_wr_max(self, bps_wr_max):
        """Sets the bps_wr_max of this NvmfSubsystemCreationParams.


        :param bps_wr_max: The bps_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_wr_max: float
        """

        self._bps_wr_max = bps_wr_max

    @property
    def bps_rd_max_length(self):
        """Gets the bps_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_rd_max_length

    @bps_rd_max_length.setter
    def bps_rd_max_length(self, bps_rd_max_length):
        """Sets the bps_rd_max_length of this NvmfSubsystemCreationParams.


        :param bps_rd_max_length: The bps_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_rd_max_length: float
        """

        self._bps_rd_max_length = bps_rd_max_length

    @property
    def bps_rd_max(self):
        """Gets the bps_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_rd_max

    @bps_rd_max.setter
    def bps_rd_max(self, bps_rd_max):
        """Sets the bps_rd_max of this NvmfSubsystemCreationParams.


        :param bps_rd_max: The bps_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_rd_max: float
        """

        self._bps_rd_max = bps_rd_max

    @property
    def bps_max_length(self):
        """Gets the bps_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_max_length

    @bps_max_length.setter
    def bps_max_length(self, bps_max_length):
        """Sets the bps_max_length of this NvmfSubsystemCreationParams.


        :param bps_max_length: The bps_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_max_length: float
        """

        self._bps_max_length = bps_max_length

    @property
    def bps_max(self):
        """Gets the bps_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_max

    @bps_max.setter
    def bps_max(self, bps_max):
        """Sets the bps_max of this NvmfSubsystemCreationParams.


        :param bps_max: The bps_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_max: float
        """

        self._bps_max = bps_max

    @property
    def iops_wr_max_length(self):
        """Gets the iops_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_wr_max_length

    @iops_wr_max_length.setter
    def iops_wr_max_length(self, iops_wr_max_length):
        """Sets the iops_wr_max_length of this NvmfSubsystemCreationParams.


        :param iops_wr_max_length: The iops_wr_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_wr_max_length: float
        """

        self._iops_wr_max_length = iops_wr_max_length

    @property
    def iops_wr_max(self):
        """Gets the iops_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_wr_max

    @iops_wr_max.setter
    def iops_wr_max(self, iops_wr_max):
        """Sets the iops_wr_max of this NvmfSubsystemCreationParams.


        :param iops_wr_max: The iops_wr_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_wr_max: float
        """

        self._iops_wr_max = iops_wr_max

    @property
    def iops_rd_max_length(self):
        """Gets the iops_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_rd_max_length

    @iops_rd_max_length.setter
    def iops_rd_max_length(self, iops_rd_max_length):
        """Sets the iops_rd_max_length of this NvmfSubsystemCreationParams.


        :param iops_rd_max_length: The iops_rd_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_rd_max_length: float
        """

        self._iops_rd_max_length = iops_rd_max_length

    @property
    def iops_rd_max(self):
        """Gets the iops_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_rd_max

    @iops_rd_max.setter
    def iops_rd_max(self, iops_rd_max):
        """Sets the iops_rd_max of this NvmfSubsystemCreationParams.


        :param iops_rd_max: The iops_rd_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_rd_max: float
        """

        self._iops_rd_max = iops_rd_max

    @property
    def iops_max_length(self):
        """Gets the iops_max_length of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_max_length

    @iops_max_length.setter
    def iops_max_length(self, iops_max_length):
        """Sets the iops_max_length of this NvmfSubsystemCreationParams.


        :param iops_max_length: The iops_max_length of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_max_length: float
        """

        self._iops_max_length = iops_max_length

    @property
    def iops_max(self):
        """Gets the iops_max of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_max

    @iops_max.setter
    def iops_max(self, iops_max):
        """Sets the iops_max of this NvmfSubsystemCreationParams.


        :param iops_max: The iops_max of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_max: float
        """

        self._iops_max = iops_max

    @property
    def bps_wr(self):
        """Gets the bps_wr of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_wr of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_wr

    @bps_wr.setter
    def bps_wr(self, bps_wr):
        """Sets the bps_wr of this NvmfSubsystemCreationParams.


        :param bps_wr: The bps_wr of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_wr: float
        """

        self._bps_wr = bps_wr

    @property
    def bps_rd(self):
        """Gets the bps_rd of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps_rd of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps_rd

    @bps_rd.setter
    def bps_rd(self, bps_rd):
        """Sets the bps_rd of this NvmfSubsystemCreationParams.


        :param bps_rd: The bps_rd of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps_rd: float
        """

        self._bps_rd = bps_rd

    @property
    def bps(self):
        """Gets the bps of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The bps of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._bps

    @bps.setter
    def bps(self, bps):
        """Sets the bps of this NvmfSubsystemCreationParams.


        :param bps: The bps of this NvmfSubsystemCreationParams.  # noqa: E501
        :type bps: float
        """

        self._bps = bps

    @property
    def iops_wr(self):
        """Gets the iops_wr of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_wr of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_wr

    @iops_wr.setter
    def iops_wr(self, iops_wr):
        """Sets the iops_wr of this NvmfSubsystemCreationParams.


        :param iops_wr: The iops_wr of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_wr: float
        """

        self._iops_wr = iops_wr

    @property
    def iops_rd(self):
        """Gets the iops_rd of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops_rd of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops_rd

    @iops_rd.setter
    def iops_rd(self, iops_rd):
        """Sets the iops_rd of this NvmfSubsystemCreationParams.


        :param iops_rd: The iops_rd of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops_rd: float
        """

        self._iops_rd = iops_rd

    @property
    def iops(self):
        """Gets the iops of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The iops of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: float
        """
        return self._iops

    @iops.setter
    def iops(self, iops):
        """Sets the iops of this NvmfSubsystemCreationParams.


        :param iops: The iops of this NvmfSubsystemCreationParams.  # noqa: E501
        :type iops: float
        """

        self._iops = iops

    @property
    def description(self):
        """Gets the description of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The description of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NvmfSubsystemCreationParams.


        :param description: The description of this NvmfSubsystemCreationParams.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def nqn_whitelist(self):
        """Gets the nqn_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The nqn_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._nqn_whitelist

    @nqn_whitelist.setter
    def nqn_whitelist(self, nqn_whitelist):
        """Sets the nqn_whitelist of this NvmfSubsystemCreationParams.


        :param nqn_whitelist: The nqn_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501
        :type nqn_whitelist: str
        """

        self._nqn_whitelist = nqn_whitelist

    @property
    def ip_whitelist(self):
        """Gets the ip_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501


        :return: The ip_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._ip_whitelist

    @ip_whitelist.setter
    def ip_whitelist(self, ip_whitelist):
        """Sets the ip_whitelist of this NvmfSubsystemCreationParams.


        :param ip_whitelist: The ip_whitelist of this NvmfSubsystemCreationParams.  # noqa: E501
        :type ip_whitelist: str
        """

        self._ip_whitelist = ip_whitelist

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NvmfSubsystemCreationParams):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NvmfSubsystemCreationParams):
            return True

        return self.to_dict() != other.to_dict()
